safety_bt_node:
  ros__parameters:
    # Battery thresholds
    low_battery_threshold: 20.0
    battery_ok_threshold: 85.0

    # Collision thresholds
    collision_distance: 0.5
    safe_distance: 0.75

    # Robot motion
    rotation_speed: 10.0
    monitor_rate: 10.0
